MACHINE = "raspberrypi3-64"
# The default is a downloads directory under TOPDIR which is the build directory.
DL_DIR ?= "/home/ehab/Documents/ITI_9Months/Yocto/shared-build/downloads"
# The default is a sstate-cache directory under TOPDIR.
SSTATE_DIR ?= "/home/ehab/Documents/ITI_9Months/Yocto/shared-build/sstate-cache"
# The default is a tmp directory under TOPDIR.
TMPDIR = "/home/ehab/Documents/ITI_9Months/Yocto/shared-build/tmp"
DISTRO ?= "poky"

EXTRA_IMAGE_FEATURES ?= "debug-tweaks"
USER_CLASSES ?= "buildstats"
PATCHRESOLVE = "noop"
BB_DISKMON_DIRS ??= "\
    STOPTASKS,${TMPDIR},1G,100K \
    STOPTASKS,${DL_DIR},1G,100K \
    STOPTASKS,${SSTATE_DIR},1G,100K \
    STOPTASKS,/tmp,100M,100K \
    HALT,${TMPDIR},100M,1K \
    HALT,${DL_DIR},100M,1K \
    HALT,${SSTATE_DIR},100M,1K \
    HALT,/tmp,10M,1K"

PACKAGECONFIG:append:pn-qemu-system-native = " sdl"
CONF_VERSION = "2"
# Number of threads to use for building
BB_NUMBER_THREADS = "12"
# Enable console on serial port - to show login shell after booting
SERIAL_CONSOLES = "115200;ttyAMA0"
RPI_EXTRA_CONFIG = "dtoverlay=miniuart-bt"
CMDLINE_ROOT_PARTITION = "/dev/nfs nfsroot=192.168.2.1:/srv/nfs/rootfs,v3,tcp ip=192.168.2.2:192.168.2.1::255.255.255.0::eth0:off"
