ctrl_interface=/var/run/wpa_supplicant
ctrl_interface_group=0
update_config=1
country=EG

network={
    ssid="xxxxx"
    scan_ssid=1
    psk="xxxxxxxx"
    priority=3
}

network={
    ssid="xxxx"
    scan_ssid=1
    psk="xxxxxxxx"
    priority=3
}

network={
    ssid="xxxx"
    scan_ssid=1
    psk="xxxxxxxx"
    priority=4
}